export const trailProjects = [
  {
    id: 'livedmatch',
    name: 'LivedMatch',
    category: 'PEOPLE × RESEARCH',
    place: 'The trailhead',
    mile: '00.0',
    altitude: '3,240',
    color: '#da693e',
    description:
      'Good things happen when the right paths cross. Connecting lived experience with research that matters.',
    tags: ['Matching platform', 'Human-centered design'],
    status: 'Live platform',
    note: 'A place for researchers and people with lived experience to find each other, build trust, and move better research forward.',
    screen: [55, 80],
  },
  {
    id: 'aicorn',
    name: 'AICorn',
    category: 'SMALL SEEDS. BIG SYSTEMS.',
    place: 'Ponderosa grove',
    mile: '01.4',
    altitude: '3,860',
    color: '#799442',
    description:
      'A little orchestration goes a long way. Your backlog, your agents, one place to keep it all growing.',
    tags: ['AI orchestration', 'React / Go'],
    status: 'Open source',
    note: 'An open source integration for coordinating agents and work through Conductor, with a human in control.',
    screen: [39, 69],
  },
  {
    id: 'switchback',
    name: 'Switchback',
    category: 'FIND YOUR OWN WAY',
    place: 'The switchbacks',
    mile: '02.8',
    altitude: '4,520',
    color: '#e4a53d',
    description:
      'Less planning in tabs. More getting out there. An offline-first field guide for the beautifully unplanned.',
    tags: ['Maps', 'Offline-first'],
    status: 'Imagined concept',
    note: 'A concept for saving trails, making a loose weekend plan, and keeping the important bits available when the signal disappears. An invented project for this collection.',
    screen: [66, 60],
  },
  {
    id: 'kernel',
    name: 'Kernel',
    category: 'SMALL CORE. CLEAR INTENT.',
    place: 'Granite lookout',
    mile: '04.1',
    altitude: '5,180',
    color: '#8199aa',
    description:
      'Every action leaves a trace. A small, local agent runtime that remembers how it got here.',
    tags: ['Local-first', 'Rust · proposed'],
    status: 'Proposed concept',
    note: 'An exploration of a local agent runtime where actions are inspectable and memory is part of the system, from the beginning.',
    screen: [47, 51],
  },
  {
    id: 'current',
    name: 'Current',
    category: 'MAKE THE INVISIBLE VISIBLE',
    place: 'Alpine creek',
    mile: '05.3',
    altitude: '5,760',
    color: '#6c9ca5',
    description:
      'A quieter way to understand the energy running through a home. Small signals, meaningful changes.',
    tags: ['Data visualization', 'Energy'],
    status: 'Imagined concept',
    note: 'An invented home energy dashboard: clear daily patterns, useful comparisons, and room to notice what changes. A visual exploration, not a released product.',
    screen: [61, 43],
  },
  {
    id: 'fieldnotes',
    name: 'Fieldnotes',
    category: 'LEAVE ROOM FOR DISCOVERY',
    place: 'The high country',
    mile: '06.8',
    altitude: '6,420',
    color: '#cba676',
    description:
      'For the thought that arrives miles from a desk. A pocket-sized home for observations, sketches, and unfinished ideas.',
    tags: ['Personal knowledge', 'Local-first'],
    status: 'Imagined concept',
    note: 'An invented digital field journal connecting observations by place and time. Capture a fragment now; find the thread later. Part of this adventure-themed concept collection.',
    screen: [50, 36],
  },
] as const;

export type TrailProject = (typeof trailProjects)[number];
